---
- name: Check for required variables.
  fail:
    msg: "Variable '{{ required_var }}' is not defined"
  when: lookup('vars', required_var) is not defined
  loop_control:
    loop_var: required_var
  loop:
    - service_name
    - docker_image

- name: Validate service name.
  fail:
    msg: "'{{ service_name }}' is not a valid service name"
  when: service_name is not match("[A-Za-z0-9\.\-_]+")

- name: Install service definition.
  become: yes
  template:
    src: systemd.service.j2
    dest: "{{ systemd_install_path }}/{{ service_name }}.service"
  notify:
    - reload systemd daemon
    - restart service

- name: Enable service.
  become: yes
  service:
    name: "{{ service_name }}"
    state: started
    enabled: True
