---
- name: Converge
  hosts: all
  roles:
    - role: geerlingguy.docker
      vars:
        docker_install_compose: false
  tasks:
    - name: Include chameleon.docker_service
      include_role:
        name: chameleon.docker_service
      vars:
        service_name: foo
        docker_image: centos:7
