---
- name: Converge
  hosts: all
  tasks:
    - name: Include chameleon.docker-service
      include_role:
        name: chameleon.docker-service
      vars:
        service_name: foo
        docker_image: centos:7
