---
dependency:
  name: galaxy
  options:
    role-file: test-requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-centos:7}"
    command: /sbin/init
    capabilities:
      - NET_ADMIN
      - NET_RAW
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
