name: "Release collection"
on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3
      - name: Publish Ansible role to Galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          # Your personal Galaxy key found under Galaxy -> Your Profile -> Preferences -> API Key
          galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
          # The git branch you want to upload.
          git_branch: master
          # The (relative) location of your role.
          path: ./
